version: '3.7'
services:
  postgresql:
    image: roko1384/12-alpine:latest
    ports:
    - '3306:3306'
    volumes:
    - ./data:/var/lib/roko1384/12-alpine
    environment:
    - roko1384/12-alpine_RANDOM_ROOT_PASSWORD=yes
    - roko1384/12-alpine_DATABASE=app
    - roko1384/12-alpine_USER=app
    - roko1384/12-alpine_PASSWORD=9mREsvXDs9Gk89Ef